import { NgModule } from '@angular/core';
import { MatButtonModule,
         MatAutocompleteModule,
         MatCheckboxModule,
         MatFormFieldModule,
         MatInputModule,
         MatRadioModule,
         MatSelectModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatMenuModule,
         MatSidenavModule,
         MatToolbarModule,
         MatCardModule,
         MatDividerModule,
         MatExpansionModule,
         MatGridListModule,
         MatListModule,
         MatStepperModule,
         MatTabsModule,
         MatTreeModule,
         MatButtonToggleModule,
         MatBadgeModule,
         MatChipsModule,
         MatIconModule,
         MatProgressSpinnerModule,
         MatProgressBarModule,
         MatRippleModule,
         MatBottomSheetModule,
         MatDialogModule,
         MatSnackBarModule,
         MatTooltipModule,
         MatPaginatorModule,
         MatSortModule,
         MatTableModule,
         MatNativeDateModule,
         MatDatepickerModule
 } from '@angular/material';


const MaterialComponents = [
  MatButtonModule,
  MatAutocompleteModule,
  MatCheckboxModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatFormFieldModule,
  MatInputModule,
  MatRadioModule,
  MatSelectModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatSidenavModule,
  MatToolbarModule,
  MatCardModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatListModule,
  MatStepperModule,
  MatTabsModule,
  MatTreeModule,
  MatButtonToggleModule,
  MatBadgeModule,
  MatChipsModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatRippleModule,
  MatBottomSheetModule,
  MatDialogModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatPaginatorModule,
  MatSortModule,
  MatTableModule
];

@NgModule({
  imports: [MaterialComponents],
  exports: [MaterialComponents]
})
export class MaterialModule { }
